from __future__ import annotations

from pathlib import Path

PROJECT_NAME = "StoryCut"

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
UPLOADS_DIR = DATA_DIR / "uploads"
TRANSCRIPTIONS_DIR = DATA_DIR / "transcriptions"
OUTPUTS_DIR = DATA_DIR / "outputs"
TEMP_DIR = DATA_DIR / "temp"
TRANSCRIPTS_DIR = OUTPUTS_DIR / "transcripts"
SUBTITLED_VIDEOS_DIR = OUTPUTS_DIR / "subtitled_videos"

DEFAULT_WHISPER_MODEL = "medium"
DEFAULT_DUPLICATE_THRESHOLD = 87
DEFAULT_MATCH_THRESHOLD = 80
DEFAULT_SILENCE_THRESHOLD_DB = -40
DEFAULT_MIN_SILENCE_DURATION_MS = 700
DEFAULT_PRE_SPEECH_PADDING_MS = 150
DEFAULT_POST_SPEECH_PADDING_MS = 250
DEFAULT_START_PADDING_SECONDS = 0.20
DEFAULT_END_PADDING_SECONDS = 0.15
DEFAULT_SHORTS_SUBTITLE_MARGIN_V = 260
DEFAULT_SHORTS_SUBTITLE_FONT_SIZE = 94
DEFAULT_SHORTS_SUBTITLE_OUTLINE_SIZE = 3
DEFAULT_SHORTS_SUBTITLE_SHADOW_SIZE = 1
DEFAULT_SHORTS_SUBTITLE_SPACING = 0.4
DEFAULT_SHORTS_SUBTITLE_COLOR = "#FFFFFF"
DEFAULT_SHORTS_SUBTITLE_HIGHLIGHT_COLOR = "#FFD84D"
DEFAULT_SHORTS_SUBTITLE_BASE_FONT = "Bebas Neue"
DEFAULT_SHORTS_SUBTITLE_ACCENT_FONT = "Playfair Display"
DEFAULT_SHORTS_SUBTITLE_ACCENT_LAST_WORD = True
SHORTS_SUBTITLE_FONT_OPTIONS = (
    "Montserrat",
    "Playfair Display",
    "Bebas Neue",
)

SHORTS_DIR = OUTPUTS_DIR / "shorts"
DAVINCI_DIR = OUTPUTS_DIR / "davinci"


def ensure_directories() -> None:
    for path in (
        DATA_DIR,
        UPLOADS_DIR,
        TRANSCRIPTIONS_DIR,
        OUTPUTS_DIR,
        TEMP_DIR,
        TRANSCRIPTS_DIR,
        SUBTITLED_VIDEOS_DIR,
        SHORTS_DIR,
        DAVINCI_DIR,
    ):
        path.mkdir(parents=True, exist_ok=True)

